### ISSUE TITLE
decay van raid bases checken

### ISSUE THREAD

**Issue by jeffrey-opdam** [rust-escalations/configuration#3]

**Comment by TheDudeIV4** [comment]
wel als je ze even "aanval" en daarna wacht en dat om de x minuten doe, dan reset je de timer van het event zodat je je raid kan voltooien.

**Comment by jeremybreeschoten** [comment]
@jeffrey-opdam / @TheDudeIV4 Volgens mij kunnen we deze sluiten? ik heb deze wipe niks gehoord of gemerkt.

**Comment by jeremybreeschoten** [comment]
Je_Re_My — vandaag om 15:57
heeft iemand nog iets opgemerkt over de decay van de raid bases?
volgens mij gaat dat goed eh? Dan kunnen we dat issue ook sluiten
Phoenix-One — vandaag om 15:58
yup
TheDude — vandaag om 16:02
Klopta denk dat dat goed gaat
