### ISSUE TITLE
Cargo minder vaak laten komen (2u + marge)

### ISSUE THREAD

**Issue by jeffrey-opdam** [rust-escalations/configuration#6]

**Comment by jeffrey-opdam** [comment]
I do not see configuration or a plugin for this one.

**Comment by jeremybreeschoten** [comment]
https://umod.org/plugins/automated-events maybe we can use?

**Comment by jeffrey-opdam** [comment]
netjes, deze zou die andere 2 plugins kunnen vervangen

**Comment by jeremybreeschoten** [comment]
> 

Dan heb je inderdaad 1 plugin voor meerdere dingen!

**Comment by jeffrey-opdam** [comment]
maak maar een pull request ;)

**Comment by jeremybreeschoten** [comment]
uhhhhmmmmm?
